my_translation_ui:
    resource: "@MyTranslationUIBundle/Controller/"
    type:     annotation
    prefix:   /_trans

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

JMSTranslationBundle_ui:
    resource: ../../vendor/jms/translation-bundle/JMS/TranslationBundle/Controller
    type:     annotation
    prefix:   /_trans

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
