app:
    resource: "@AppBundle/Controller/"
    type:     annotation

JMSTranslationBundle_ui:
    resource: @JMSTranslationBundle/Controller/
    type:     annotation
    prefix:   /_trans

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
